"""Git diff parser: splits unified diff / patch strings into structured per-file objects and hunks."""

from dataclasses import dataclass, field
import re
from typing import List, Optional


@dataclass
class DiffHunk:
    """Represents a single unified diff hunk (@@ ... @@)."""
    old_start: int
    old_length: int
    new_start: int
    new_length: int
    header: str
    lines: List[str] = field(default_factory=list)

    @property
    def added_lines(self) -> List[str]:
        return [l[1:] for l in self.lines if l.startswith('+')]

    @property
    def deleted_lines(self) -> List[str]:
        return [l[1:] for l in self.lines if l.startswith('-')]

    @property
    def context_lines(self) -> List[str]:
        return [l[1:] for l in self.lines if l.startswith(' ')]

    def to_patch_text(self) -> str:
        return f"{self.header}\n" + "\n".join(self.lines)


@dataclass
class FileDiff:
    """Represents the complete diff for a single file."""
    old_path: Optional[str]
    new_path: Optional[str]
    change_type: str  # "ADDED", "DELETED", "MODIFIED", "RENAMED", "BINARY"
    is_binary: bool = False
    hunks: List[DiffHunk] = field(default_factory=list)
    raw_header_lines: List[str] = field(default_factory=list)

    @property
    def path(self) -> str:
        """Preferred display path for the file."""
        if self.new_path and self.new_path != "/dev/null":
            return self.new_path
        return self.old_path or "unknown"

    @property
    def additions(self) -> int:
        return sum(len(h.added_lines) for h in self.hunks)

    @property
    def deletions(self) -> int:
        return sum(len(h.deleted_lines) for h in self.hunks)

    def to_patch_text(self) -> str:
        """Reconstruct a clean patch string for this file."""
        headers = "\n".join(self.raw_header_lines)
        if self.is_binary:
            return f"{headers}\n[Binary file changed]"
        hunk_texts = "\n".join(h.to_patch_text() for h in self.hunks)
        return f"{headers}\n{hunk_texts}" if headers else hunk_texts


@dataclass
class ParsedDiff:
    """Aggregated parsed diff containing all files and total statistics."""
    files: List[FileDiff] = field(default_factory=list)

    @property
    def total_files(self) -> int:
        return len(self.files)

    @property
    def total_additions(self) -> int:
        return sum(f.additions for f in self.files)

    @property
    def total_deletions(self) -> int:
        return sum(f.deletions for f in self.files)

    def get_file(self, path: str) -> Optional[FileDiff]:
        for f in self.files:
            if f.path == path or f.old_path == path or f.new_path == path:
                return f
        return None


HUNK_HEADER_PATTERN = re.compile(
    r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@(.*)$"
)


def _clean_git_path(path: str) -> str:
    """Strips leading a/ or b/ prefixes commonly generated by git diff."""
    if path.startswith("a/") or path.startswith("b/"):
        return path[2:]
    return path


def parse_diff(raw_diff: str) -> ParsedDiff:
    """
    Parses a raw unified git diff / patch string into a ParsedDiff structure.
    
    Handles:
    - Standard `diff --git a/file b/file` headers
    - New, deleted, renamed, and binary files
    - Multiple hunks per file
    - Multi-line hunk context and stats
    """
    if not raw_diff or not raw_diff.strip():
        return ParsedDiff(files=[])

    lines = raw_diff.splitlines()
    files: List[FileDiff] = []
    
    current_file: Optional[FileDiff] = None
    current_hunk: Optional[DiffHunk] = None
    in_headers = True

    i = 0
    while i < len(lines):
        line = lines[i]

        # Check for start of a new file diff
        if line.startswith("diff --git "):
            if current_hunk and current_file:
                current_file.hunks.append(current_hunk)
                current_hunk = None
            if current_file:
                files.append(current_file)

            # Match: diff --git a/path b/path
            parts = line.split(" ")
            old_p = None
            new_p = None
            if len(parts) >= 4:
                old_p = _clean_git_path(parts[2])
                new_p = _clean_git_path(parts[3])

            current_file = FileDiff(
                old_path=old_p,
                new_path=new_p,
                change_type="MODIFIED",
                is_binary=False,
                hunks=[],
                raw_header_lines=[line]
            )
            in_headers = True
            i += 1
            continue

        if current_file is None:
            # Fallback if diff doesn't start with 'diff --git' (e.g. standard patch with --- / +++)
            if line.startswith("--- "):
                current_file = FileDiff(
                    old_path=_clean_git_path(line[4:].strip()),
                    new_path=None,
                    change_type="MODIFIED",
                    raw_header_lines=[line]
                )
                in_headers = True
                i += 1
                continue
            i += 1
            continue

        # File header processing
        if in_headers:
            if line.startswith("new file mode"):
                current_file.change_type = "ADDED"
                current_file.raw_header_lines.append(line)
            elif line.startswith("deleted file mode"):
                current_file.change_type = "DELETED"
                current_file.raw_header_lines.append(line)
            elif line.startswith("rename from "):
                current_file.change_type = "RENAMED"
                current_file.old_path = line[12:].strip()
                current_file.raw_header_lines.append(line)
            elif line.startswith("rename to "):
                current_file.change_type = "RENAMED"
                current_file.new_path = line[10:].strip()
                current_file.raw_header_lines.append(line)
            elif "Binary files " in line and " differ" in line:
                current_file.is_binary = True
                current_file.change_type = "BINARY"
                current_file.raw_header_lines.append(line)
            elif line.startswith("--- "):
                path_part = line[4:].strip().split("\t")[0]
                if path_part == "/dev/null":
                    current_file.change_type = "ADDED"
                    current_file.old_path = None
                else:
                    current_file.old_path = _clean_git_path(path_part)
                current_file.raw_header_lines.append(line)
            elif line.startswith("+++ "):
                path_part = line[4:].strip().split("\t")[0]
                if path_part == "/dev/null":
                    current_file.change_type = "DELETED"
                    current_file.new_path = None
                else:
                    current_file.new_path = _clean_git_path(path_part)
                current_file.raw_header_lines.append(line)
            elif line.startswith("@@ "):
                # Start of first hunk
                in_headers = False
                match = HUNK_HEADER_PATTERN.match(line)
                if match:
                    old_start = int(match.group(1))
                    old_len = int(match.group(2)) if match.group(2) else 1
                    new_start = int(match.group(3))
                    new_len = int(match.group(4)) if match.group(4) else 1
                    current_hunk = DiffHunk(
                        old_start=old_start,
                        old_length=old_len,
                        new_start=new_start,
                        new_length=new_len,
                        header=line,
                        lines=[]
                    )
            else:
                current_file.raw_header_lines.append(line)
            i += 1
            continue

        # Inside hunks
        if line.startswith("@@ "):
            if current_hunk:
                current_file.hunks.append(current_hunk)
            match = HUNK_HEADER_PATTERN.match(line)
            if match:
                old_start = int(match.group(1))
                old_len = int(match.group(2)) if match.group(2) else 1
                new_start = int(match.group(3))
                new_len = int(match.group(4)) if match.group(4) else 1
                current_hunk = DiffHunk(
                    old_start=old_start,
                    old_length=old_len,
                    new_start=new_start,
                    new_length=new_len,
                    header=line,
                    lines=[]
                )
            else:
                current_hunk = None
            i += 1
            continue

        if current_hunk is not None:
            if line.startswith(("+", "-", " ", "\\")):
                current_hunk.lines.append(line)
            elif line.strip() == "":
                # Often empty line in unified diff is an empty context line
                current_hunk.lines.append(" " + line)
            else:
                # If an unrecognized line occurs, treat as context or note
                current_hunk.lines.append(" " + line)

        i += 1

    # Cleanup trailing file/hunk
    if current_hunk and current_file:
        current_file.hunks.append(current_hunk)
    if current_file:
        files.append(current_file)

    return ParsedDiff(files=files)
